"""
Render path for Arista EOS CLI (``show running-config`` form).

Public function: :func:`render_intent` — :class:`CanonicalIntent`
in, EOS CLI text out.

Emits the same surfaces the parse path consumes: hostname, DNS,
NTP, SNMP (community / location / contact / trap-host / v3 user),
local users, VRF instances, VLANs, interfaces (with IPv4/IPv6,
VRF binding, switchport mode, LAG membership, MTU, shutdown),
LAG stub stanzas, ``interface Vxlan1`` (with ``vxlan source-
interface`` + ``vxlan udp-port`` + per-VNI mappings + L3-VNI
mappings for VRF Type-5), ``router bgp <asn>`` blocks (for L3
VRF RD/RT and EVPN MAC-VRF per-VLAN bindings), and static routes.

Extracted verbatim from ``codec.py`` during the parse/render
split; behaviour is identical to the prior in-class
implementation.  The codec module's ``render()`` method is now a
one-line delegator to :func:`render_intent`.
"""

from __future__ import annotations

import re
from typing import Any

from ...canonical.intent import CanonicalIntent
from ..base import RenderError


def render_intent(tree: Any) -> str:
    """Render a :class:`CanonicalIntent` as Arista EOS CLI text."""
    if not isinstance(tree, CanonicalIntent):
        raise RenderError(
            "arista_eos: tree must be a CanonicalIntent.",
            yang_path="/",
        )

    out: list[str] = []
    out.append("! Generated by netconfig-translator (arista_eos target)")
    out.append("!")
    if tree.hostname:
        out.append(f"hostname {tree.hostname}")
        out.append("!")

    if tree.dns_servers:
        for dns in tree.dns_servers:
            out.append(f"ip name-server vrf default {dns}")
        out.append("!")
    if tree.domain:
        out.append(f"dns domain {tree.domain}")
        out.append("!")
    if tree.ntp_servers:
        for ntp in tree.ntp_servers:
            out.append(f"ntp server {ntp}")
        out.append("!")

    if tree.snmp is not None:
        if tree.snmp.community:
            out.append(f"snmp-server community {tree.snmp.community} ro")
        if tree.snmp.location:
            out.append(f"snmp-server location {tree.snmp.location}")
        if tree.snmp.contact:
            out.append(f"snmp-server contact {tree.snmp.contact}")
        for host in tree.snmp.trap_hosts:
            out.append(f"snmp-server host {host}")
        # SNMPv3 users.  ``aes128`` canonical → ``aes`` on EOS wire
        # (Arista accepts both but the bare form is the
        # platform-natural default); ``aes192`` / ``aes256`` emit
        # one-token form.  Users with no auth / no priv emit the
        # bare ``v3`` line — noAuthNoPriv is a valid USM mode.
        for u in tree.snmp.v3_users:
            parts = [f"snmp-server user {u.name} {u.group or 'v3group'} v3"]
            if u.auth_protocol:
                parts.append(
                    f"auth {u.auth_protocol} {u.auth_passphrase}"
                )
            if u.priv_protocol:
                wire_priv = (
                    "aes" if u.priv_protocol == "aes128"
                    else u.priv_protocol
                )
                parts.append(f"priv {wire_priv} {u.priv_passphrase}")
            out.append(" ".join(parts))
        if (
            tree.snmp.community or tree.snmp.location
            or tree.snmp.contact or tree.snmp.trap_hosts
            or tree.snmp.v3_users
        ):
            out.append("!")

    # --- Local users ---
    if tree.local_users:
        for user in tree.local_users:
            parts = [f"username {user.name}"]
            if user.privilege_level and user.privilege_level != 1:
                parts.append(f"privilege {user.privilege_level}")
            if user.role:
                parts.append(f"role {user.role}")
            if user.hashed_password:
                vendor, _, tail = user.hashed_password.partition(":")
                if vendor == "arista" and ":" in tail:
                    # Round-trip: ``arista:<alg>:<hash>`` →
                    # ``secret <alg> <hash>``.
                    alg, _, hsh = tail.partition(":")
                    parts.append(f"secret {alg} {hsh}")
                else:
                    # Foreign hash — emit as opaque secret 5.
                    parts.append(f"secret 5 {user.hashed_password}")
            else:
                parts.append("nopassword")
            out.append(" ".join(parts))
        out.append("!")

    # --- VRF instances (GAP 6) — declare every canonical L3 VRF
    #     via ``vrf instance <name>``.  RD + RTs emit later
    #     under router-bgp / vrf <name>.  GAP-EVPN-1 mac-vrf
    #     entries are NOT L3 VRFs and skip this block — they're
    #     emitted purely under router-bgp / vlan <vid>.
    l3_vrfs = [
        ri for ri in tree.routing_instances
        if ri.instance_type != "mac-vrf"
    ]
    if l3_vrfs:
        for ri in l3_vrfs:
            out.append(f"vrf instance {ri.name}")
        out.append("!")

    # --- VLANs ---
    if tree.vlans:
        for vlan in tree.vlans:
            out.append(f"vlan {vlan.id}")
            if vlan.name:
                out.append(f"   name {vlan.name}")
        out.append("!")

    # --- Interfaces ---
    # Build LAG mode lookup so member interfaces can emit the
    # matching ``channel-group N mode <mode>`` line.  Arista LAGs
    # live on the member side — the canonical tree carries
    # `lag_member_of` on each member + a `CanonicalLAG` record in
    # `tree.lags`; render needs both.
    lag_mode_by_name = {lag.name: (lag.mode or "active") for lag in tree.lags}
    for iface in tree.interfaces:
        out.append(f"interface {iface.name}")
        if iface.description:
            out.append(f"   description {iface.description}")
        # L3 flip needed when we emit an IP address on a port that
        # doesn't already indicate L3 (Ethernet<N> physical).
        if iface.ipv4_addresses and iface.name.lower().startswith(
            "ethernet"
        ):
            out.append("   no switchport")
        # GAP 6: per-interface VRF membership.  Must emit BEFORE
        # ``ip address`` so EOS correctly binds the IP into the
        # VRF's routing table.
        if iface.vrf:
            out.append(f"   vrf {iface.vrf}")
        if iface.switchport_mode == "access":
            out.append("   switchport mode access")
            if iface.access_vlan is not None:
                out.append(
                    f"   switchport access vlan {iface.access_vlan}"
                )
        elif iface.switchport_mode == "trunk":
            out.append("   switchport mode trunk")
            if iface.trunk_allowed_vlans:
                vlist = ",".join(str(v) for v in iface.trunk_allowed_vlans)
                out.append(
                    f"   switchport trunk allowed vlan {vlist}"
                )
        for addr in iface.ipv4_addresses:
            out.append(
                f"   ip address {addr.ip}/{addr.prefix_length}"
            )
        # GAP-EVPN-3: IPv6 addresses.  Link-local form re-emits
        # the explicit ``link-local`` keyword; global form emits
        # plain ``ipv6 address X/Y``.
        for v6 in iface.ipv6_addresses:
            if v6.scope == "link-local":
                out.append(
                    f"   ipv6 address {v6.ip}/{v6.prefix_length} link-local"
                )
            else:
                out.append(
                    f"   ipv6 address {v6.ip}/{v6.prefix_length}"
                )
        # LAG membership: ``channel-group N mode <mode>`` on member
        # Ethernet interfaces.  Arista (like Cisco IOS) puts this
        # on the child side, not the Port-Channel stanza.
        if iface.lag_member_of:
            m = re.match(r"^Port-Channel(\d+)$", iface.lag_member_of)
            if m is not None:
                chan_id = m.group(1)
                mode = lag_mode_by_name.get(
                    iface.lag_member_of, "active",
                )
                # Normalise canonical mode strings to EOS CLI tokens.
                if mode == "static":
                    mode_token = "on"
                elif mode == "passive":
                    mode_token = "passive"
                else:
                    mode_token = "active"
                out.append(
                    f"   channel-group {chan_id} mode {mode_token}"
                )
        if iface.mtu is not None:
            out.append(f"   mtu {iface.mtu}")
        if not iface.enabled:
            out.append("   shutdown")
        out.append("!")

    # --- LAGs (channel-group lines live on member interfaces; we
    #     also emit ``interface Port-ChannelN`` stubs so the
    #     config is self-consistent) ---
    existing_names = {i.name for i in tree.interfaces}
    for lag in tree.lags:
        if lag.name not in existing_names:
            out.append(f"interface {lag.name}")
            out.append("!")

    # --- Vxlan1 (GAP 6) — EOS carries VLAN-to-VNI + VRF-to-L3-VNI
    #     mappings inside a single ``interface Vxlan1`` stanza.
    #     GAP-EVPN-2: source-interface + udp-port come from the
    #     CanonicalVxlan records (per-switch values stamped on
    #     every VNI mapping at parse-time); fall back to
    #     ``Loopback0`` / ``4789`` when no record carries a non-
    #     default value (e.g. a render of a tree built purely from
    #     a VRF / l3_vni scenario with no L2 VNIs).
    has_l3_vnis = any(
        ri.l3_vni is not None for ri in tree.routing_instances
    )
    if tree.vxlan_vnis or has_l3_vnis:
        src_iface = "Loopback0"
        for v in tree.vxlan_vnis:
            if v.source_interface:
                src_iface = v.source_interface
                break
        udp_port = 4789
        for v in tree.vxlan_vnis:
            if v.udp_port and v.udp_port != 4789:
                udp_port = v.udp_port
                break
        out.append("interface Vxlan1")
        out.append(f"   vxlan source-interface {src_iface}")
        out.append(f"   vxlan udp-port {udp_port}")
        for v in tree.vxlan_vnis:
            out.append(f"   vxlan vlan {v.vlan_id} vni {v.vni}")
        for ri in tree.routing_instances:
            if ri.l3_vni is not None:
                out.append(f"   vxlan vrf {ri.name} vni {ri.l3_vni}")
        out.append("!")

    # --- router bgp blocks (GAP 6 + GAP-EVPN-1) — emit
    #     ``router bgp <asn>`` carrying:
    #       * ``vrf <name> / rd / route-target ...`` for L3 VRFs
    #         (instance_type == "vrf")
    #       * ``vlan <vid> / rd / route-target ...`` for per-VLAN
    #         EVPN MAC-VRF bindings (instance_type == "mac-vrf",
    #         GAP-EVPN-1).  vid is reverse-looked-up from the
    #         routing-instance name → CanonicalVlan.name match.
    #     ASN defaults to a placeholder since CanonicalIntent
    #     doesn't model BGP config beyond what VRFs need;
    #     operators re-emit as needed.
    ris_with_bgp_meta = [
        ri for ri in tree.routing_instances
        if ri.route_distinguisher or ri.rt_imports or ri.rt_exports
    ]
    if ris_with_bgp_meta:
        # Build a name→vlan_id lookup for the MAC-VRF emit path.
        vid_by_name = {
            v.name: v.id for v in tree.vlans if v.name
        }
        out.append("router bgp 65000")
        for ri in ris_with_bgp_meta:
            out.append("   !")
            if ri.instance_type == "mac-vrf":
                # Reverse-lookup the VLAN id by name.  Fall back
                # to parsing ``VLAN<N>`` synthetic-form (the
                # parse path uses this when CanonicalVlan.name
                # is empty).  If neither works, skip — render
                # would emit an invalid ``vlan <name>`` line.
                vid = vid_by_name.get(ri.name)
                if vid is None and ri.name.startswith("VLAN"):
                    try:
                        vid = int(ri.name[len("VLAN"):])
                    except ValueError:
                        vid = None
                if vid is None:
                    # Can't resolve back to a VID — skip the
                    # block rather than emit nonsense.
                    continue
                out.append(f"   vlan {vid}")
            else:
                out.append(f"   vrf {ri.name}")
            if ri.route_distinguisher:
                out.append(f"      rd {ri.route_distinguisher}")
            # Use ``route-target both`` for matched import/export
            # pairs (compact + canonical-friendly); emit separate
            # import/export lines when they diverge.
            if (
                ri.rt_imports == ri.rt_exports and ri.rt_imports
            ):
                for rt in ri.rt_imports:
                    out.append(f"      route-target both {rt}")
            else:
                for rt in ri.rt_imports:
                    out.append(f"      route-target import evpn {rt}")
                for rt in ri.rt_exports:
                    out.append(f"      route-target export evpn {rt}")
            if ri.instance_type == "mac-vrf":
                # ``redistribute learned`` is the canonical EOS
                # default for MAC-VRF blocks — emit it so a
                # round-trip of a fresh-from-Arista MAC-VRF
                # continues to advertise locally-learned MACs.
                out.append("      redistribute learned")
        out.append("!")

    # --- Static routes ---
    if tree.static_routes:
        for route in tree.static_routes:
            if route.gateway:
                out.append(
                    f"ip route {route.destination} {route.gateway}"
                )
        out.append("!")
        out.append("ip routing")
        out.append("!")

    out.append("end")
    return "\n".join(out) + "\n"
