"""
Render path for Cisco IOS-XE CLI (``running-config`` form).

Public function: :func:`render_intent` — :class:`CanonicalIntent`
in, IOS-XE ``show running-config`` text out.

Bidirectional codec — pairs with :func:`parse_intent` from
:mod:`.parse` for round-trip.

Coverage spans every Tier-1 + Tier-2 canonical surface this codec
also parses on the source side: hostname / domain / DNS / NTP /
syslog / interfaces (physical, SVI, Loopback, Port-channel, Tunnel) /
VLANs / static routes / DHCP pools / SNMP (v1/v2c + v3) / local users
/ RADIUS / VRFs.  Anything outside the canonical surface (firewall
ACLs, QoS policies, BGP/OSPF, IKEv2) falls through silently — same
convention as every other codec.

Output format mirrors the Cisco wire form an operator would paste
into a console: ``!``-delimited stanzas, dotted-decimal netmasks,
``no shutdown``/``shutdown`` on interfaces.  Ordering is intentionally
close to a real ``show running-config`` (banner / hostname / users /
VRFs / interfaces / VLANs / routing / SNMP / etc.) so the diff
against a real capture stays readable.

Extracted verbatim from ``codec.py`` during the parse/render split;
behaviour is identical to the prior in-class implementation.  The
codec module's ``render()`` method is now a one-line delegator to
:func:`render_intent`.

Internal helpers (``_prefix_to_mask``, ``_cidr_to_dest_mask``,
``_extract_lag_number``, ``_split_cisco_hash``) live here because
they are render-only.  The inverse parse helper
(``_mask_to_prefix``) lives in :mod:`.parse` and the two never
cross sibling boundaries.
"""

from __future__ import annotations

import ipaddress
import re
from typing import Any

from ..._user_secrets import (
    classify_hash,
    format_review_comment,
    is_migratable,
)
from ...canonical.intent import (
    CanonicalIntent,
    CanonicalInterface,
    CanonicalLAG,
)
from ..base import RenderError


def render_intent(tree: Any) -> str:
    """Render a :class:`CanonicalIntent` to IOS-XE
    ``show running-config`` text.

    Raises:
        RenderError: If *tree* is not a :class:`CanonicalIntent`.
    """
    if not isinstance(tree, CanonicalIntent):
        raise RenderError(
            "cisco_iosxe_cli: tree must be a CanonicalIntent.",
            yang_path="/",
        )

    # Materialise port-centric switchport state from VLAN-centric
    # membership lists.  Required for cross-vendor renders from
    # codecs that emit no per-port stanzas (Aruba AOS-S
    # ``vlan N / untagged 1/1-1/47`` form, OPNsense ``<vlans>``-
    # only).  Idempotent + additive — same-vendor round-trips
    # where interfaces are already populated are no-ops.
    from ...canonical.transforms import project_vlan_to_switchport
    project_vlan_to_switchport(tree)

    out: list[str] = []

    # --- header banner ---
    out.append("Building configuration...")
    out.append("")
    out.append("! Generated by netconfig translator (cisco_iosxe_cli)")
    out.append("!")

    # --- service / system globals ---
    out.append("service timestamps debug datetime msec")
    out.append("service timestamps log datetime msec")
    out.append("!")
    if tree.hostname:
        out.append(f"hostname {tree.hostname}")
        out.append("!")
    if tree.domain:
        out.append(f"ip domain name {tree.domain}")
        out.append("!")

    # --- local users ---
    # Cisco form: `username X privilege N secret <type> <hash>`.
    # Canonical ``hashed_password`` preserves whatever opaque hash the
    # source captured.  Same-vendor (Cisco→Cisco) round-trip carries
    # the type-5 / 8 / 9 marker through verbatim.  Cross-vendor hashes
    # (Arista sha512, OPNsense bcrypt $2y$, FortiGate ENC, ...) are
    # NOT consumable by IOS-XE's ``secret`` parser — IOS-XE only
    # accepts type 0 / 5 / 8 / 9.  Before this gate the renderer
    # leaked the literal foreign hash under ``secret 5`` (security
    # disclosure: the bcrypt hash leaks on the wire) AND tagged
    # bcrypt as md5crypt (wrong type marker).  We now consult the
    # shared :mod:`netconfig.migration._user_secrets` policy and emit
    # a comment-form ``review:`` line in IOS comment syntax (``! ``)
    # when the hash is unmigratable.  Empty password renders
    # ``nopassword`` (legitimate Cisco form).
    for u in tree.local_users:
        if u.hashed_password and not is_migratable(
            u.hashed_password, "cisco_iosxe_cli",
        ):
            algorithm, _payload = classify_hash(u.hashed_password)
            out.append(
                format_review_comment(
                    u.name, algorithm, comment_syntax="exclamation",
                    target_label="Cisco IOS-XE",
                )
            )
            continue
        parts = [f"username {u.name}"]
        if u.privilege_level and u.privilege_level != 1:
            parts.append(f"privilege {u.privilege_level}")
        if u.role and u.role not in ("admin", "operator"):
            # Cisco supports `role <name>` only on platforms that
            # enabled `aaa new-model` — emit only when the role is
            # non-canonical (admin/operator are derived defaults
            # from privilege; emitting them as roles would be
            # noisy and frequently wrong).
            pass
        if not u.hashed_password:
            parts.append("nopassword")
        else:
            hash_type, hash_val = _split_cisco_hash(u.hashed_password)
            parts.append(f"secret {hash_type} {hash_val}")
        out.append(" ".join(parts))
    if tree.local_users:
        out.append("!")

    # --- DNS / NTP / syslog ---
    for srv in tree.dns_servers:
        out.append(f"ip name-server {srv}")
    if tree.dns_servers:
        out.append("!")
    for srv in tree.ntp_servers:
        out.append(f"ntp server {srv}")
    if tree.ntp_servers:
        out.append("!")
    for srv in tree.syslog_servers:
        out.append(f"logging host {srv}")
    if tree.syslog_servers:
        out.append("!")

    # --- VRFs (CanonicalRoutingInstance → vrf definition) ---
    # Cisco IOS-XE syntax: ``vrf definition <name>`` with nested
    # rd / route-target / address-family stanzas.  Empty RD/RT lists
    # render the bare definition (still valid; lets per-interface
    # ``vrf forwarding`` references resolve at parse time).
    for vrf in tree.routing_instances:
        if not vrf.name:
            continue
        out.append(f"vrf definition {vrf.name}")
        if vrf.description:
            out.append(f" description {vrf.description}")
        if vrf.route_distinguisher:
            out.append(f" rd {vrf.route_distinguisher}")
        if vrf.rt_imports or vrf.rt_exports:
            out.append(" address-family ipv4")
            for rt in vrf.rt_imports:
                out.append(f"  route-target import {rt}")
            for rt in vrf.rt_exports:
                out.append(f"  route-target export {rt}")
            out.append(" exit-address-family")
        out.append("!")

    # --- interfaces ---
    # LAG members carry ``lag_member_of=<lag_name>``.  Cisco needs
    # the matching ``interface Port-channel<N>`` declared as a
    # peer top-level stanza, with the member's ``channel-group N
    # mode <mode>`` line inside the physical iface.  We emit
    # Port-channel stanzas FIRST (so they're declared before
    # member references) then the physical / SVI / Loopback /
    # Tunnel interfaces.
    lag_by_name: dict[str, CanonicalLAG] = {
        lag.name: lag for lag in tree.lags
    }
    # Sort: Port-channel first (so they bind before member refs),
    # then by canonical kind (physical, SVI, Loopback, Tunnel,
    # everything else).  Within each kind, sort by NATURAL port-
    # name order so output is operator-natural ("1/0/1" before
    # "1/0/2" before "1/0/10") regardless of the order parse /
    # synthesis populated tree.interfaces.  Without the natural
    # sort, set-iteration-driven synthesis from VLAN-centric
    # source codecs (Aruba "untagged 1/1-1/47" expansion) emitted
    # interfaces in random hash order — visually disorienting
    # for operators reading the rendered config.
    from ...canonical.transforms import _natural_port_sort_key

    def _iface_sort_key(iface: CanonicalInterface):
        n = iface.name.lower()
        if n.startswith("port-channel") or iface.name in lag_by_name:
            kind = 0
        elif n.startswith("vlan"):
            kind = 1
        elif n.startswith("loopback"):
            kind = 2
        elif n.startswith("tunnel"):
            kind = 3
        else:
            kind = 4
        return (kind, _natural_port_sort_key(iface.name))

    ordered_ifaces = sorted(tree.interfaces, key=_iface_sort_key)

    # Empty-stub elision (mirrors Junos commit `0fdf7e9`, finding #8
    # in tests/fixtures/real/user_smoke_findings.md).  Cross-vendor
    # source codecs preserve the source's port-name verbatim on the
    # canonical CanonicalInterface (OPNsense ``igc0`` / ``ixl0``,
    # MikroTik ``ether1``, etc.).  Without elision the IOS-XE render
    # leaks ``interface igc0`` literal stubs that have no body — pure
    # noise for an operator reading the rendered config and not even
    # accepted as a valid port name on the target device.  We emit
    # the bare ``interface NAME`` line ONLY when one of the following
    # holds:
    #
    #   (a) the canonical record carries any renderable body
    #       (description / IPs / MTU / shutdown / L2 / LAG / VRF),
    #   (b) the interface is referenced from a VLAN port-list
    #       (untagged / tagged) — Cisco needs the iface declared so
    #       the access/trunk binding has somewhere to live, OR
    #   (c) the interface name matches an IOS-XE physical-port shape
    #       (preserves round-trip for same-vendor renders that
    #       capture only Tier-3 grammar on a port).
    #
    # Names referenced from VLAN port lists.
    vlan_referenced_names: set[str] = set()
    for v in tree.vlans:
        for n in v.tagged_ports:
            vlan_referenced_names.add(n)
        for n in v.untagged_ports:
            vlan_referenced_names.add(n)

    for iface in ordered_ifaces:
        body: list[str] = []
        if iface.description:
            body.append(f" description {iface.description}")
        if iface.vrf:
            body.append(f" vrf forwarding {iface.vrf}")
        # IPv4 addresses — Cisco needs dotted-decimal masks.
        for addr in iface.ipv4_addresses:
            mask = _prefix_to_mask(addr.prefix_length)
            body.append(f" ip address {addr.ip} {mask}")
        # GAP-EVPN-3: IPv6 addresses — IOS-XE uses CIDR natively
        # (no dotted-mask form for v6).  Link-local re-emits the
        # explicit keyword.
        for v6 in iface.ipv6_addresses:
            if v6.scope == "link-local":
                body.append(
                    f" ipv6 address {v6.ip}/{v6.prefix_length} link-local"
                )
            else:
                body.append(
                    f" ipv6 address {v6.ip}/{v6.prefix_length}"
                )
        # Switchport — emit the mode FIRST (operator-natural
        # ordering), then EVERY captured switchport sub-attribute
        # regardless of mode.  Cisco IOS-XE tolerates declaring
        # ``switchport access vlan`` on a trunk port and
        # ``switchport trunk allowed vlan`` on an access port:
        # both are harmless on the inactive-mode side and become
        # active if the operator later flips the mode.  Real
        # captures from production switches sometimes carry both
        # (e.g. a port pre-configured for both possible modes
        # before deployment) — gating the render by mode would
        # silently drop the inactive-mode declarations and break
        # canonical-stable round-trip on those captures.
        if iface.switchport_mode in ("access", "trunk"):
            body.append(f" switchport mode {iface.switchport_mode}")
        if iface.access_vlan is not None:
            body.append(
                f" switchport access vlan {iface.access_vlan}"
            )
        if iface.voice_vlan is not None:
            body.append(
                f" switchport voice vlan {iface.voice_vlan}"
            )
        if iface.trunk_native_vlan is not None:
            body.append(
                f" switchport trunk native vlan "
                f"{iface.trunk_native_vlan}"
            )
        if iface.trunk_allowed_vlans:
            vlan_list = ",".join(
                str(v) for v in iface.trunk_allowed_vlans
            )
            body.append(
                f" switchport trunk allowed vlan {vlan_list}"
            )
        if iface.mtu is not None:
            body.append(f" mtu {iface.mtu}")
        # LAG-membership marker.  Mode normalisation: canonical
        # ``active`` → LACP active; ``passive`` → LACP passive;
        # ``static`` → mode ``on`` (no LACP).
        if iface.lag_member_of:
            lag = lag_by_name.get(iface.lag_member_of)
            lag_num = _extract_lag_number(iface.lag_member_of)
            mode = (lag.mode if lag else "active") or "active"
            wire_mode = {
                "active": "active",
                "passive": "passive",
                "static": "on",
                "on": "on",
            }.get(mode.lower(), "active")
            if lag_num is not None:
                body.append(
                    f" channel-group {lag_num} mode {wire_mode}"
                )
        # Enabled state — Cisco default is ``no shutdown`` so
        # we only emit when explicitly disabled.  Parsers that
        # didn't see ``shutdown`` leave enabled=True.
        if not iface.enabled:
            body.append(" shutdown")
        if iface.dhcp_client:
            body.append(" ip address dhcp")

        # Elision predicate.
        is_native_port = bool(_IS_CISCO_PHYSICAL_PORT_RE.match(iface.name))
        is_vlan_referenced = iface.name in vlan_referenced_names
        if not body and not is_native_port and not is_vlan_referenced:
            # Foreign port name with no body and no incoming reference —
            # skip entirely.  Suppresses ``interface igc0`` /
            # ``interface ether1`` etc. from cross-vendor renders.
            continue
        if not body and is_vlan_referenced and not is_native_port:
            # Foreign port referenced from a VLAN port list — keep the
            # bare ``interface NAME`` line so the membership has a
            # binding target, but flag for operator review.
            out.append(f"interface {iface.name}")
            out.append(
                f"! interface {iface.name} -- review: foreign port "
                f"name preserved from source vendor; rename to a "
                f"native IOS-XE port before deploy"
            )
            out.append("!")
            continue
        out.append(f"interface {iface.name}")
        out.extend(body)
        out.append("!")

    # --- VLANs ---
    # Cisco form: ``vlan N`` + ``  name X``.  Port membership is
    # carried on the per-interface ``switchport access vlan`` /
    # ``trunk allowed vlan`` lines above; this block is just the
    # VLAN-database declaration.
    for vlan in tree.vlans:
        out.append(f"vlan {vlan.id}")
        if vlan.name:
            out.append(f" name {vlan.name}")
    if tree.vlans:
        out.append("!")

    # --- static routes ---
    for route in tree.static_routes:
        dest, mask = _cidr_to_dest_mask(route.destination)
        tail = ""
        if route.metric and route.metric > 0:
            tail = f" {route.metric}"
        target = route.gateway or route.interface
        if not target:
            continue
        out.append(f"ip route {dest} {mask} {target}{tail}")
    if tree.static_routes:
        out.append("!")

    # --- DHCP server pools ---
    for pool in tree.dhcp_servers:
        pool_name = (pool.interface or pool.network or "POOL").replace(
            "/", "_",
        )
        out.append(f"ip dhcp pool {pool_name}")
        if pool.network:
            net, mask = _cidr_to_dest_mask(pool.network)
            out.append(f" network {net} {mask}")
        if pool.gateway:
            out.append(f" default-router {pool.gateway}")
        for d in pool.dns_servers:
            out.append(f" dns-server {d}")
        if pool.domain_name:
            out.append(f" domain-name {pool.domain_name}")
        if pool.lease_time and pool.lease_time != 86400:
            hours = pool.lease_time // 3600
            out.append(f" lease 0 {hours}")
        out.append("!")

    # --- RADIUS servers ---
    for server in tree.radius_servers:
        out.append(f"radius server {server.host}")
        out.append(f" address ipv4 {server.host} auth-port "
                   f"{server.auth_port} acct-port {server.acct_port}")
        if server.key:
            out.append(f" key {server.key}")
        out.append("!")

    # --- SNMP block ---
    if tree.snmp is not None:
        s = tree.snmp
        if s.community:
            out.append(f"snmp-server community {s.community} RO")
        if s.location:
            out.append(f"snmp-server location {s.location}")
        if s.contact:
            out.append(f"snmp-server contact {s.contact}")
        for host in s.trap_hosts:
            out.append(f"snmp-server host {host}")
        # SNMPv3 USM users.  Cisco syntax pairs auth/priv with
        # the v3 keyword; ``aes128`` canonical → ``aes 128`` two
        # tokens; ``aes192``/``aes256`` similarly split.
        for u in s.v3_users:
            line = [
                f"snmp-server user {u.name} {u.group or 'v3group'} v3",
            ]
            if u.auth_protocol:
                line.append(
                    f"auth {u.auth_protocol} {u.auth_passphrase}"
                )
            if u.priv_protocol:
                if u.priv_protocol == "aes128":
                    line.append(f"priv aes 128 {u.priv_passphrase}")
                elif u.priv_protocol == "aes192":
                    line.append(f"priv aes 192 {u.priv_passphrase}")
                elif u.priv_protocol == "aes256":
                    line.append(f"priv aes 256 {u.priv_passphrase}")
                elif u.priv_protocol == "aes":
                    line.append(f"priv aes 128 {u.priv_passphrase}")
                else:
                    line.append(
                        f"priv {u.priv_protocol} {u.priv_passphrase}"
                    )
            out.append(" ".join(line))
        if (s.community or s.location or s.contact
                or s.trap_hosts or s.v3_users):
            out.append("!")

    # --- raw_sections passthrough ---
    # Tier-3 raw blocks the source carried through.  Emit as-is
    # under ``! raw_section: <name>`` markers so the operator can
    # see what didn't auto-translate.  Skipped if empty.
    for name, body in tree.raw_sections.items():
        out.append(f"! raw_section: {name}")
        for ln in body.splitlines():
            out.append(ln)
        out.append("!")

    out.append("end")
    return "\n".join(out) + "\n"


# Cisco IOS-XE physical-port name shapes.  Used by the empty-stub
# elision predicate (mirrors the Junos pattern in
# ``juniper_junos/render.py::_IS_JUNOS_PHYSICAL_PORT_RE``) to decide
# whether a content-free canonical iface is "really there" (same-
# vendor source where the parser captured only Tier-3 grammar) or a
# foreign port name leaking through from a cross-vendor source
# (OPNsense ``igc0``, MikroTik ``ether1``, etc.) that should be
# elided from the rendered config.  Covers the IOS-XE families an
# operator would expect to see on real hardware (including the
# wide-and-weird Batfish-corpus families like ``Crypto-Engine``,
# ``Wideband-Cable``, ``Wlan-GigabitEthernet``, ``Dot11Radio``).
# Match is case-insensitive because real IOS-XE accepts both
# ``Vlan100`` and ``vlan100`` (parse-side treats them identically).
_CISCO_PORT_PREFIX_ALTS = "|".join((
    # Ethernet families.
    r"FastEthernet",
    r"GigabitEthernet",
    r"TenGigabitEthernet",
    r"TwentyFiveGigE",
    r"FortyGigabitEthernet",
    r"HundredGigE",
    r"AppGigabitEthernet",
    r"Ethernet",
    # Aggregate / virtual.
    r"Port-channel",
    r"Loopback",
    r"Vlan",
    r"Tunnel-ip6",
    r"Tunnel-ip",
    r"Tunnel",
    r"Management",
    r"BDI",
    r"Serial",
    r"Async",
    r"Null",
    r"VirtualPortGroup",
    r"Multilink",
    r"Dialer",
    r"Group-Async",
    r"BVI",
    r"pseudowire",
    r"nve",
    r"GMPLS",
    r"Voice",
    # Wireless / Cable / WiFi families.
    r"Dot11Radio",
    r"Wlan-GigabitEthernet",
    r"Wlan-ap",
    r"Wideband-Cable",
    r"Modular-Cable",
    r"Cable",
    r"Crypto-Engine",
))
_IS_CISCO_PHYSICAL_PORT_RE = re.compile(
    rf"^(?:{_CISCO_PORT_PREFIX_ALTS})[\s\d/.:]*$",
    re.IGNORECASE,
)


def _prefix_to_mask(prefix: int) -> str:
    """Convert a CIDR prefix length to a dotted-decimal subnet mask.

    Inverse of :func:`netconfig.migration.codecs.cisco_iosxe_cli.parse._mask_to_prefix`.
    Used by render() because Cisco IOS-XE's ``ip address X Y`` form
    requires dotted-decimal — every other shipped codec uses CIDR
    natively, so the canonical tree holds prefix lengths and we
    expand on render.
    """
    if not (0 <= prefix <= 32):
        raise RenderError(
            f"cisco_iosxe_cli: prefix length {prefix} out of range",
            yang_path="/interfaces/interface/ipv4/address/prefix-length",
        )
    mask_int = (0xFFFFFFFF << (32 - prefix)) & 0xFFFFFFFF if prefix else 0
    return str(ipaddress.IPv4Address(mask_int))


def _cidr_to_dest_mask(cidr: str) -> tuple[str, str]:
    """Split a ``X.X.X.X/N`` CIDR into ``(network, dotted_mask)``.

    Used by render() for ``ip route DEST MASK GATEWAY`` and
    ``network DEST MASK`` inside DHCP pools — both Cisco syntaxes
    expect dotted-decimal masks.  Tolerates inputs that are already
    in ``DEST MASK`` form (returns them unchanged) and treats
    ``"default"`` / ``"0.0.0.0/0"`` as default-route shorthand.
    """
    if not cidr:
        return ("0.0.0.0", "0.0.0.0")
    if cidr.lower() == "default":
        return ("0.0.0.0", "0.0.0.0")
    if "/" not in cidr:
        # Plain IP — assume host route.
        return (cidr, "255.255.255.255")
    dest, _, prefix_str = cidr.partition("/")
    try:
        prefix = int(prefix_str)
    except ValueError:
        return (dest, "255.255.255.255")
    return (dest, _prefix_to_mask(prefix))


def _extract_lag_number(lag_name: str) -> int | None:
    """Pull the numeric tail off a LAG name (``Port-channel10`` → 10,
    ``Trk5`` → 5, ``ae0`` → 0).  Used by render() to emit the
    ``channel-group N mode <X>`` line on member interfaces — Cisco's
    LAG syntax is integer-keyed regardless of the source vendor's
    naming convention.  Returns None for names with no trailing
    digits."""
    m = re.search(r"(\d+)\s*$", lag_name or "")
    if m is None:
        return None
    try:
        return int(m.group(1))
    except ValueError:
        return None


def _split_cisco_hash(hashed: str) -> tuple[str, str]:
    """Map a canonical ``hashed_password`` blob into Cisco's
    ``secret <type> <hash>`` two-token form.

    Cisco encrypted-password types:
      * 0 — plaintext (rare; used when operator pastes plaintext)
      * 5 — MD5-crypt
      * 7 — Cisco's reversible XOR (legacy; weak)
      * 8 — PBKDF2-SHA-256
      * 9 — scrypt

    Canonical hashed_password preserves whatever shape the source
    parser captured.  This helper assumes the caller has ALREADY
    consulted :func:`netconfig.migration._user_secrets.is_migratable`
    and confirmed the hash is consumable by IOS-XE — the un-
    migratable path emits a review-comment line above instead of
    calling this function.  Recognised migratable shapes:

      * ``"<type-digit> <hash>"`` (digits 5 / 8 / 9) — round-trip
        form produced by the Cisco parser.  Honours the captured
        type marker.
      * ``"<vendor>:<alg>:<payload>"`` / ``"<alg>:<payload>"`` —
        normalised tagged form.  ``5`` / ``md5crypt`` / ``8`` / ``9``
        map to their corresponding type digit.
      * ``$1$...`` raw — md5crypt → emit ``5 $1$...``
      * ``$8$...`` / ``$9$...`` raw — emit ``8 ..`` / ``9 ..``
      * Anything else — treat as plaintext → ``secret 0 <literal>``.
    """
    if not hashed:
        return ("0", "")
    # Vendor-tagged forms (``cisco:5:$1$..``, ``md5crypt:$1$..``,
    # ``9:$9$..``).  Use classify_hash for normalisation so we don't
    # duplicate parsing logic.
    algorithm, payload = classify_hash(hashed)
    if algorithm in {"5", "md5crypt"}:
        return ("5", payload or hashed)
    if algorithm == "7":
        return ("7", payload or hashed)
    if algorithm == "8":
        return ("8", payload or hashed)
    if algorithm == "9":
        return ("9", payload or hashed)
    # ``classify_hash`` returns ``("plaintext", ...)`` for raw $1$..
    # blobs (no leading ``5 `` marker, no vendor tag).  Detect and
    # promote to type-5 here so cross-vendor sources that store md5
    # crypt as a bare ``$1$..`` still emit under the right tag.
    if hashed.startswith("$9$"):
        return ("9", hashed)
    if hashed.startswith("$8$"):
        return ("8", hashed)
    if hashed.startswith("$1$"):
        return ("5", hashed)
    # Plaintext literal (only path reachable via the migratable-gate
    # for non-empty values that weren't algorithm-tagged).  IOS-XE
    # ``secret 0`` is the documented form for unhashed passwords; the
    # device hashes on commit.
    return ("0", hashed)
